### ISSUE TITLE
Allow to install older versions in a "safe" place

### ISSUE THREAD

**Issue by ghost** [Unvanquished/updater#110]
The problem this feature would solve is that testing if a change is a regression is not easy at all:

* have to know where the older releases are (if they still can be run, but this is not a huge problem for rather recent versions I guess?)
* install them manually
* launch the engine with the proper parameters so that it does not mess the user's usual configuration

The delta-pack feature here also does not helps, as there is strictly no way to identify which .dpk files are necessary to run a specific version of unvanquished, considering the fact 0.53 notably required 0.52 files. Well, there *is* a way: to unzip those (for people knowing they're zip files) and to read the DEPS files... each of those. One can't even rely on the versions in names, as they mean nothing (i.e. tex-common_2.2.dpk and tex-common_2.3.dpk)

**Comment by illwieckz** [comment]
Isn't it easier to just download an old release from https://dl.unvanquished.net/release/ ?

Across time we may change the release file layout (it's rare, but it happens), so even if we had a way to force the updater to download an old version, it may not extract it properly.

**Comment by ghost** [comment]
> Isn't it easier to just download an old release from https://dl.unvanquished.net/release/ ?

hm... maybe. Do those release files have a README or something that gives a command line that is certain to not corrupt the normal folders of the user?

**Comment by slipher** [comment]
This feature is too niche to be worth implementing with our limited resources. Universal zips should suffice for people interested in old versions.
