### ISSUE TITLE
Keyboard shortcut to force the splash screen to end

### ISSUE THREAD

**Issue by slipher** [Unvanquished/updater#128]
We could add a way to skip the splash screen, for when 3 seconds is too long to wait. How about pressing the spacebar twice?

@VReaperV thoughts?

Note: there is a `--splashms` updater command line option that controls the duration, but obviously this is hardly convenient. And reducing the duration all the time is not great because then it may be difficult to access the settings page. And also this serves as the timeout for the request that checks the version numbers. On multiple occasions I've had issues with this taking several seconds (due to DNS issues).

**Comment by illwieckz** [comment]
Not a bad idea!

**Comment by illwieckz** [comment]
Maybe also add a “play” button next to the option icon?

I guess the idea is to skip the check for an update?

**Comment by slipher** [comment]
> I guess the idea is to skip the check for an update?

No. The idea is to cut short the splash screen which always displays for 3 seconds. Actually if the shortcut is pressed, I plan to still do an update if one was detected in time.

**Comment by VReaperV** [comment]
Sounds good, though personally I very rarely use the updater, usually just launch daemon directly/through a debugger. I do agree with illwieckz that there either needs to be a button in the UI for that or some indication of which button you need to press (like "Press [spacebar] to skip"). One button press is probably enough.
