### ISSUE TITLE
Hangs at near-completion: Error extracting update.

### ISSUE THREAD

**Issue by mjstahlberg** [Unvanquished/updater#15]
For me, the updater got stuck showing a progress of `740.3 / 740.7 MiB`, `00:00:00 left`, still showing `DL: 4.9 MiB/s UL: 0.0 Byte/s` while there is no more progress.

The console shows:
```
QFontDatabase: Cannot find font directory /usr/local/lib/fonts.
Note that Qt no longer ships fonts. Deploy some (from http://dejavu-fonts.org for exampl
qml: conn.updaterUpdate=false
qml: Installing to […]
qml: Download started
qml: Torrent downloaded
qml: Download started
qml: Error extracting update
qml: Error extracting update
```

**Comment by mjstahlberg** [comment]
Restarting the updater inmmediately unpacked correctly and I was able to start the game.

**Comment by DolceTriade** [comment]
I had a branch open at one point that would be more verbose about errors (i also need to be WAAY better about exposing these errors to users in ways that are not the console...). I should get back to that... It's not clear why it failed extracting the first time.

**Comment by mjstahlberg** [comment]
If you are using the torrent and the unpacking fails you could use the torrent checksum to verify-and-fix the data and try again. I'm not sure if this would have helped here, maybe the unpacking issue was unrelated to data validity.

**Comment by slipher** [comment]
Closing this as I assume no one can reproduce it.
