### ISSUE TITLE
QSslSocket: cannot resolve SSLv2_client_method

### ISSUE THREAD

**Issue by illwieckz** [Unvanquished/updater#17]
I built the updater to have a look, and I got some ssl-related errors, and nothing is downloaded, neither blog entries neither the game itself, I guess the following json error occurs on an empty file due to a timeout or something like that.

```
qt.network.ssl: QSslSocket: cannot resolve SSLv2_client_method
qt.network.ssl: QSslSocket: cannot resolve SSLv2_server_method
file:///…/Qt5.9.1/5.9.1/gcc_64/qml/QtQuick/Dialogs/DefaultFileDialog.qml:210:25: QML ListView: Binding loop detected for property "model"
qrc:/News.qml:30: SyntaxError: JSON.parse: Parse error
```

**Comment by DolceTriade** [comment]
Can you check if you get this on the latest prebuilt version? I haven't committed anything since then. This sounds like a QT issue and not being able to dynamically load an SSL library.

**Comment by illwieckz** [comment]
This happened with an old build of mine, seems related to some mismatch with old build and newer distro.
