### ISSUE TITLE
[Debian buster] Launcher not working

### ISSUE THREAD

**Issue by mole99** [Unvanquished/updater#24]
First of all, I would like to thank all of you for working on the new Unvanquished version and the launcher!

I immediately downloaded the new launcher from the official website and tried to execute it.

---

My system and qt version:

> uname -a
Linux debian-dell 4.18.0-3-amd64 #1 SMP Debian 4.18.20-2 (2018-11-23) x86_64 GNU/Linux

>lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux buster/sid
Release:	testing
Codename:	buster

>qmake --version
QMake version 3.1
Using Qt version 5.11.2 in /usr/lib/x86_64-linux-gnu

The result is as follows:

![launcher](https://user-images.githubusercontent.com/3877395/49729410-b43bef00-fc75-11e8-81e7-63b078658cf9.png)

With output from the terminal:

> ./updater 
QSslSocket: cannot resolve CRYPTO_num_locks
QSslSocket: cannot resolve CRYPTO_set_id_callback
QSslSocket: cannot resolve CRYPTO_set_locking_callback
QSslSocket: cannot resolve ERR_free_strings
QSslSocket: cannot resolve sk_new_null
QSslSocket: cannot resolve sk_push
QSslSocket: cannot resolve sk_free
QSslSocket: cannot resolve sk_num
QSslSocket: cannot resolve sk_pop_free
QSslSocket: cannot resolve sk_value
QSslSocket: cannot resolve SSL_library_init
QSslSocket: cannot resolve SSL_load_error_strings
QSslSocket: cannot resolve SSLv3_client_method
QSslSocket: cannot resolve SSLv23_client_method
QSslSocket: cannot resolve SSLv3_server_method
QSslSocket: cannot resolve SSLv23_server_method
QSslSocket: cannot resolve X509_STORE_CTX_get_chain
QSslSocket: cannot resolve OPENSSL_add_all_algorithms_noconf
QSslSocket: cannot resolve OPENSSL_add_all_algorithms_conf
QSslSocket: cannot resolve SSLeay
QSslSocket: cannot resolve SSLeay_version
QSslSocket: cannot call unresolved function CRYPTO_num_locks
QSslSocket: cannot call unresolved function CRYPTO_set_id_callback
QSslSocket: cannot call unresolved function CRYPTO_set_locking_callback
QSslSocket: cannot call unresolved function SSL_library_init
QSslSocket: cannot call unresolved function SSLv23_client_method
QSslSocket: cannot call unresolved function sk_num
QMutex: destroying locked mutex
QSslSocket: cannot call unresolved function CRYPTO_num_locks
QSslSocket: cannot call unresolved function CRYPTO_set_id_callback
QSslSocket: cannot call unresolved function CRYPTO_set_locking_callback
QSslSocket: cannot call unresolved function ERR_free_strings

Digging into it, it seems Debian has dropped these symbols completely from the packages:

> https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=797926

Installing libssl1.0-dev should resolve those issues:

> sudo apt install libssl1.0-dev

The output is now as follows:

> ./updater 
QSslSocket: cannot resolve SSLv3_client_method
QSslSocket: cannot resolve SSLv3_server_method

This seems to be the same issue as #17, which shouldn't be a blocking issue.

Starting the launcher, it still looks the same.

Disregarding the look of the launcher I downloaded the game, but after finishing the download a new error shows up, saying that it can't extract the update:

![launcher_extract](https://user-images.githubusercontent.com/3877395/49729792-c4a09980-fc76-11e8-99e7-1b7f039f27ee.png)

After manually extracting `linux-amd64.zip` under `/home/leo/.local/share/unvanquished` I was able to start the game by executing the daemon engine.

---

Do I need any additional packages to make the launcher work in Debian?

If any specific log files etc. are necessary, just tell me.

**Comment by FreeSlave** [comment]
Are you sure you downloaded the right updater? The executable currently is called updater2, not updater. Also just from interface it looks like you downloaded the old version.

**Comment by slipher** [comment]
The unvanquished.net home page and download page seem to have the right version. Where did you find it?

**Comment by mole99** [comment]
My bad! It seems like my browser cached the site, which was why it pointed to the old URL.

Proof that I'm not crazy (bottom left corner):

![unv](https://user-images.githubusercontent.com/3877395/49740826-5a4b2180-fc95-11e8-8131-97fffa6aa6d4.png)

After clearing the cache + cookies it now shows me the correct download link.

![launcher](https://user-images.githubusercontent.com/3877395/49740856-70f17880-fc95-11e8-89bc-5a72a04ae4e1.png)

Thank you for your help, the launcher now works like a charm!
