### ISSUE TITLE
Unvanquished does not load properly if updater runs in a terminal on Linux

### ISSUE THREAD

**Issue by illwieckz** [Unvanquished/updater#26]
Hi, it's probably related to some stdio stuff, but Unvanquished hangs at startup when launched by from the updater if the updater runs in a terminal.

If I start the updater from my desktop launcher using `[Alt+F2]` key combination or if y run the updater without attaching it to my terminal stdios using nohup (doing `nohup ./updater`), I'm able to successfully start Unvanquished from the updater. Otherwise don't.

You can see these logs:
http://pastebin.com/T4qFZjda

You get more logs if you try to restart unvanquished from updater after crashing it before (started from updater too).

```
Warn: Error writing to the terminal: Resource temporarily unavailable
Warn: Error writing to the terminal: Resource temporarily unavailable
Warn: Error writing to the terminal: Resource temporarily unavailable
Warn: Error writing to the terminal: Resource temporarily unavailable
Loading pak '/data/unvanquished/pkg/unvanquished_0.39.0.pk3'...
 Error: Crashed with signal 11: Segmentation fault
```

**Comment by illwieckz** [comment]
Latest `master` branch of QML updater reproduces the bug.

**Comment by illwieckz** [comment]
Another way to workaround the bug is to run the updater this way:

```sh
</dev/null ./updater2
```

**Comment by slipher** [comment]
Haha, I did not notice the bug before because I used the original 0.51.1 `daemon` which crashes immediately on the distro I'm testing on.

**Comment by slipher** [comment]
The situation that arises is actually identical to that when you start `daemon` from a Windows command prompt: stdout is connected to the terminal, but not stdin, and the user can freely run other commands in the meanwhile. Maybe there is something here that should be fixed on the Daemon side - perhaps it is wrongly assuming that if stdout is connected to a terminal, then stdin is also.

We could also consider launching the game with `exec` instead of in a daemonized process.

**Comment by slipher** [comment]
Reopening because I still need to check the case of launching the game after an updater update.

**Comment by ghost** [comment]
What kind of update? A big one? Because I don't remember having been used anything else than the updater to play online (and I do it a lot) while have spot no problems.

**Comment by slipher** [comment]
The updater update case is still broken. In my test the game did not respond to inputs of any kind when launched after an updater update.
