### ISSUE TITLE
Feedback on 982b53b.

### ISSUE THREAD

**Issue by mjstahlberg** [Unvanquished/updater#30]
- [x] There needs to be a guaranteed-to-be-writable default install location for every OS. For Linux (and maybe also Mac) it should be somewhere in `~` (check the Posix/XDG/etc. standards, maybe `~/.local/share` is the correct location but I'm not sure), for Windows use whatever steam uses for downloaded games, etc. That default needs to be displayed in the first-start install-selection textbox.
- [x] Changing the install location in the menu doesn't trigger any direct reaction, only after restarting the updater there is a reaction.
- [ ] The reaction to changing the install location via the menu currently is that the old install location is abandoned and the game is re-downloaded to the new location. The desired behaviour for changing an installation directory should definitely include asking the user whether they want to move the old installation over. **If** the option can be changed during a running/paused update this means that the updater has to behave accordingly.
- [x] There currently is no error for when the selected download directory is not writable. For windows, installing to the system's location for programs may be desired by users, which requires admin privileges. Only allow/implement this if the launcher can maintain these privileges over multiple executions and reboots, so that it doesn't re-request privileges _every_ startup (I'd say it's still fine for actual updates only).
- [ ] You could actually circumvent all the points above by just dictating the install location, which is what some other launchers do iirc. It would be sufficient as an option if you could change the install directory via a command line parameter only (which is stored to configuration just like now though). In that case it's fine if it's also the user's obligation to move any content before re-executing the launcher with a new install location.
- [ ] The launcher should have an uninstall option, in case the isntallation isn't properly registered with the OS which would handle the de-installation instead (which it isn't, atleast not for Linux). This is probably as easy as deleting all downloaded data after asking for confirmation.
- [x] The launcher doesn't need a Quit button. What it does need is a Play button which also replaces the Update button. To be precise, the Update button as such isn't needed either as launching the launcher means that you want to (update and) play the game in as few clicks as possible. Thus, all that is needed is a Play button that is greyed out while an update is being downloaded or looked for.
- [x] If you insist on a pause button, integrate it into the Play button, too. It would have three states: Play (greyed out), Pause/Resume (during update), Play (launches game). Looking at other launchers, I don't see many pause buttons for the same reason as above: Either you want to update and launch the game or you don't.
- [x] When the updater fails to look for a new update (e.g. no internet connection), the Play button should become available anyway after a few seconds. This should print a warning as the text of the download bar ("Failed to update").
- [x] Use the download bar to print the subset of the log messages that is interesting to the user: "Looking for update" (while downloading the .torrent and then doing a fast-verification), "Verifying installation" (in case of a necessary or requested non-fast-verification), "Downloading (n%)", "Up to date", "Failed to update". The log should be printed to the console only, if at all (maybe add a `--debug` switch). We can use the space you currently print the log to later for news and changelogs.
- [x] The menu should offer the in-depth verification (re-checksuming) of the installation, similiar to how it's done in torrent clients.
- [ ] The menu could offer a download and upload speed limit setting. A drop down menu with "unlimited" and a few options (a range/selection of powers of two) is sufficient.
- [x] The launcher should create desktop icons on all operating systems for both the launcher (see next point) and Unvanquished itself. Atleast do the latter for now.
- [x] The latest version of the launcher needs to be shipped inside the binary packages of the torrent (prefered) **or** the launcher needs to copy itself to the installation directory for the last point to be possible (not prefered, as the launcher is never updated that way but maybe worth an intermediate solution). Some launchers would even re-launch themselves after replacing their own binary. We need a self-updatig launcher in the long run for stability, so it's best to figure out a good strategy now.
- [ ] If the launcher is shipped as part of the torrent as explained above, the (default) install location should be the directory it is launched from. Detect this, for example by looking for the binaries or at a prioritized config file that would be part of the torrent, too. This allows users who downlaoded the torrent or zip once (or got it on a flashdrive) to update it, which is an extremely cool feature for very little effort!

**Comment by slipher** [comment]
> The menu could offer a download and upload speed limit setting. A drop down menu with "unlimited" and a few options (a range/selection of powers of two) is sufficient.

I don't recall ever seeing this in any other installer, so I think we are doing well enough by having a "Pause" button. This should be sufficient if you are in a video call or something and need to stop the updater to free up bandwidth.

Other remaining items have been moved to dedicated issues.
