### ISSUE TITLE
Feedback on 40f36ca.

### ISSUE THREAD

**Issue by mjstahlberg** [Unvanquished/updater#31]
General layout/size/proportions are looking good!

This feedback is mainly based on "what other launchers do":
- [x] There are two empty toolbars in the launcher window.
- [ ] You don't need to display anything above the download bar as the bar has enough space for all relevant data. It could read "Updating 200/564 MiB (3.2 MiB/s ↓ 0 MiB/s ↑ 5:23 left)" for example. Think of the bar as the only way to communicate with the user and you will automatically strip your output down to just the currently relevant info.
- [ ] In particular, don't display the install location on the launcher window. You can have a popup window asking for an install location at first start, after that the choice would just be remembered.
- [x] The launcher errors out with "Install dir does not exist. Please select another". Of course a folder named unvanquished doesn't exist when you want to install Unvanquished, this doesn't mean the installation should fail… :stuck_out_tongue: 
- [x] In case there is an actual error with the selected download directory, it would be most convenient to re-open the install location selection dialogue. Make sure the status/progress bar is visible and shows the reason for the failure (alternatively display the reason in the dialogue).
- [x] Except for when the popup window is open on first launch, the launcher should always automatically start to download/update. The play button is the only button that the user should ever press on any subsequent launch. (And this is only true because users could want to read the news!)

**Comment by slipher** [comment]
Closing since this issue pertains to the old version's UI
