### ISSUE TITLE
Pass unv:// protocol args to unvanquished

### ISSUE THREAD

**Issue by illwieckz** [Unvanquished/updater#32]
Hi, it could be awesome to be able to do that:

```
updater unv://server:port
```

So the updater launchs the game  with that arg. With that functionality, it could be possible to use the `updater` binary path in an `unvanquished.desktop` file, so the unvanquished icon on player's desktop menu launches the updater instead of dæmon directly (so the player get news and updates before launching the game), and the protocol handler will works too.

With that, you only need one desktop file, the one who starts the updater. What do you think about it?

**Comment by ghost** [comment]
I think it works now, on some systems standard enough? Like, using gnome or KDE on mainstream, unmodified distros.

**Comment by slipher** [comment]
No. The installer creates protocol associations to daemon, not the updater.
