### ISSUE TITLE
updater does not support https on Windows

### ISSUE THREAD

**Issue by illwieckz** [Unvanquished/updater#37]
updater does not support https on Windows

**Comment by illwieckz** [comment]
Can we assume next build will support it and close this?

**Comment by slipher** [comment]
> Can we assume next build will support it and close this?

No. I have verified that aria2's https is working, but I have no idea if it is possible with Qt requests. Note that Linux also has issues - #64.

**Comment by illwieckz** [comment]
So if I assume correctly,  once #64 is fixed, **next** Linux/Windows/macOS will be able to:

1. download anything with https (updater updates, torrent file, version file) with aria2
2. may not be able to download https thing (blog post, images) with qt

Se we can already replace all non-blog urls with https ones.

**Comment by slipher** [comment]
The versions.json request is using the Qt network code

**Comment by slipher** [comment]
I tested https with the Qt network requests and it is actually working. Either it was fixed by upgrading to Qt 5.14, or the original report was mistaken (possibly confusing with the redirect issue? I haven't tested redirects.)

**Comment by slipher** [comment]
The flag `-schannel` must be passed to the configure script for Qt to support HTTPS. The old Docker build did not have this option, so probably the reason it started working was that MXE configured it with `-schannel`.
