### ISSUE TITLE
add a checkbox to start the game right after being downloaded

### ISSUE THREAD

**Issue by illwieckz** [Unvanquished/updater#48]
Right under the download bar in main ui we may add a checkbox to tell the updater to automatically run the game once download finishes.

In options, we may put another checkbox to automatically download updates once available. With the updater displaying the main ui with the news excerpt during `max(download time, arbitrary time)`  when both autodownload and autostart is activated.

**Comment by slipher** [comment]
In my opinion, it would be too disruptive to suddenly start an (often) full-screen application like Unvanquished.

To notify users that the download is finished, how about `QApplication::alert`?

**Comment by illwieckz** [comment]
> To notify users that the download is finished, how about `QApplication::alert`?

Good idea if this implementation is well integrated.
