### ISSUE TITLE
Wonky starting the game when update is complete

### ISSUE THREAD

**Issue by DolceTriade** [Unvanquished/updater#5]
needs investigation

**Comment by illwieckz** [comment]
from IRC (about alpha2 release):
>`Ishq, after downloading from scratch (with empty config etc.), I launch the updater, I trigger download, I run the game, I quit the game, then I run the updater, it does not launch the game even if download is complete
> but if I trigger download and run a second time then quit, the third updater launch runs the game

**Comment by slipher** [comment]
One possible cause for this is the situation described in the last paragraph of https://github.com/Unvanquished/updater/commit/8112410be4bced25a98bbc6ea7d3a19cd3cc0c97. Assuming it's fixed for now.
