### ISSUE TITLE
Windows: game is launched as administrator

### ISSUE THREAD

**Issue by slipher** [Unvanquished/updater#57]
When the updater is running as administrator, the game is started with administrator permissions too. We can try to run as administrator only when required (instead of always), but it is still required if Unvanquished is being installed to Program Files (as is the default). 

To start as a non-administrator, hopefully this code will work: https://github.com/microsoft/Windows-classic-samples/blob/master/Samples/Win7Samples/winui/shell/appplatform/ExecInExplorer/ExecInExplorer.cpp

**Comment by DolceTriade** [comment]
yikes
