### ISSUE TITLE
aria2 TLS broken on Linux

### ISSUE THREAD

**Issue by slipher** [Unvanquished/updater#64]
The updater-update is broken on Linux in the v0.0.5 release, and with Docker builds. This is because github.com redirects http to https, and then the certificate verification fails.

I think the problem is that the `ca-certificates` option supplied in ariadownloader.cpp is misspelled. Hopefully changing it `ca-certificate` will fix that.

**Comment by DolceTriade** [comment]
lol rip. Yes, that's probably it.

**Comment by slipher** [comment]
Fixed by https://github.com/Unvanquished/updater/commit/ca6d25122cf4dc2239f2dcfc68023c342bfed031.
