### ISSUE TITLE
Splash screen sticks at top of z-order during self-update

### ISSUE THREAD

**Issue by slipher** [Unvanquished/updater#69]
The splash screen can't be moved or minimized and is drawn on top of any other windows. The splash screen is also displayed during the entire updater update process. Since a download potentially takes a long time, it should be possible to minimize the application during an updater update.

**Comment by illwieckz** [comment]
I confirm this on Linux, I experienced this while facing #54, the window was kept on top while being stuck.

**Comment by DolceTriade** [comment]
whoops...
