### ISSUE TITLE
libc is too new

### ISSUE THREAD

**Issue by hyh19962008** [Unvanquished/updater#91]
Hi, I'm running on a Ubuntu 18.04 LTS which shipped with libc 2.26(GCC 7.5.0),  the app requires libc 2.28 so I couldn't start it. I think this is not very user-friendly. If it's possible to build the app with older version of gcc so that it can run on more Linux distro?

**Comment by illwieckz** [comment]
Hmm, maybe we may investigate building on 18.04 (I don't know how well Qt5 will be happy with it though), but is there a reason that prevents you to use the 20.04 LTS and what it is?

**Comment by hyh19962008** [comment]
Nope, I just thought that maybe it's not likely the case for most of the people speding hours to upgrade their system just to play a game / run a software.

**Comment by FreeSlave** [comment]
I agree. The software should run on the the most old distro possible if doing so does not introduce major inconveniences for development process. Thankfully with docker it's easy to check if the game will be at least buildable on older envrionments. Try it out with some older ubuntu version instead of debian buster.

**Comment by slipher** [comment]
@hyh19962008 Try [this](https://github.com/Unvanquished/updater/releases/download/v0.1.0/OlderLibcLinux.zip). I patched out a couple feature tests to disable the two symbols which have the 2.28 version ([commit](https://github.com/slipher/updater/commit/8fec9af8277d170ff997b99ee0217c15c55338c9)).

**Comment by hyh19962008** [comment]
thx, it works.

**Comment by ghost** [comment]
Should this be kept open now?
