### ISSUE TITLE
Default to Nvidia GPU on Windows 10 Optimus systems

### ISSUE THREAD

**Issue by slipher** [Unvanquished/updater#96]
On these systems there is a "Graphics settings" configuration window where you can configure which GPU you want to use on a per-application basis. The options are "Let Windows decide" (default), "Power saving" (Intel), or "High performance" (Nvidia). "Let Windows decide" seems to always pick Intel for Daemon.

We can programmatically set this preference to "High performance" by creating a registry entry in `HKEY_CURRENT_USER\SOFTWARE\Microsoft\DirectX\UserGpuPreferences` like `C:\Program Files\Unvanquished\daemon.exe    REG_SZ    GpuPreference=2;`.

It's also possible to [set this from inside the application](https://stackoverflow.com/a/17563436), but the registry method seems better since then the "Graphics settings" configurator will work as expected

**Comment by illwieckz** [comment]
The registry way looks good.

**Comment by slipher** [comment]
Might want to do this at the launch phase rather than installation, since it's apparently a per-user setting, and the process' user during the install can be different from the actual user (due to admin elevation), or there can be more than one user who wants to play the game.

In any case we should make sure not to change the key if it already exists, so that if the user changes the setting it won't be overwritten on next run/install.
